package ua.fitness.db;

import java.sql.*;

public class DatabaseManager {

    private static final String DB_URL  = "jdbc:h2:./fitness_tracker;AUTO_SERVER=TRUE";
    private static final String DB_USER = "admin";
    private static final String DB_PASS = "admin";

    private static DatabaseManager instance;
    private Connection connection;

    private DatabaseManager() {
        try {
            Class.forName("org.h2.Driver");
            connection = DriverManager.getConnection(DB_URL, DB_USER, DB_PASS);
            createTables();
        } catch (Exception e) {
            throw new RuntimeException("Помилка підключення до H2: " + e.getMessage(), e);
        }
    }

    public static synchronized DatabaseManager getInstance() {
        if (instance == null || instance.isConnectionClosed()) {
            instance = new DatabaseManager();
        }
        return instance;
    }

    public Connection getConnection() {
        return connection;
    }

    public void close() {
        try {
            if (connection != null && !connection.isClosed()) {
                connection.close();
            }
        } catch (SQLException e) {
            System.err.println("Помилка закриття з'єднання: " + e.getMessage());
        } finally {
            connection = null;
            synchronized (DatabaseManager.class) {
                if (instance == this) {
                    instance = null;
                }
            }
        }
    }

    public static synchronized void closeInstance() {
        if (instance != null) {
            instance.close();
        }
    }

    private boolean isConnectionClosed() {
        try {
            return connection == null || connection.isClosed();
        } catch (SQLException e) {
            return true;
        }
    }

    private void createTables() throws SQLException {
        try (Statement stmt = connection.createStatement()) {

            stmt.execute("""
                CREATE TABLE IF NOT EXISTS users (
                    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    name       VARCHAR(255) NOT NULL,
                    age        INT          NOT NULL,
                    gender     VARCHAR(1)   NOT NULL CHECK (gender IN ('М', 'Ж')),
                    weight     DOUBLE       NOT NULL,
                    created_at VARCHAR(50)  NOT NULL
                )
                """);

            stmt.execute("""
                CREATE TABLE IF NOT EXISTS exercise_results (
                    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    user_id       BIGINT       NOT NULL,
                    exercise_key  VARCHAR(50)  NOT NULL,
                    exercise_name VARCHAR(255) NOT NULL,
                    result        DOUBLE       NOT NULL,
                    grade         VARCHAR(50)  NOT NULL,
                    recorded_at   VARCHAR(50)  NOT NULL,
                    CONSTRAINT fk_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
                )
                """);
        }
    }
}
